export const NUS_RESIDENCES: string[] = [
  "Eusoff Hall",
  "Kent Ridge Hall",
  "King Edward VII Hall",
  "Raffles Hall",
  "Sheares Hall",
  "Temasek Hall",
  "Helix House",
  "LightHouse",
  "Pioneer House",
  "Valour House",
  "College of Alice & Peter Tan (CAPT)",
  "Residential College 4 (RC4)",
  "Ridge View Residential College (RVRC)",
  "Tembusu College",
  "Acacia College",
  "Prince George's Park Residence (PGPR)",
  "UTown Residence (UTR)",
];
